### ISSUE TITLE
你是这篇论文的作者之一吗

### ISSUE THREAD

**Issue by zccoder** [akuxcw/GridMask#1]

**Comment by akuxcw** [comment]
Yes

**Comment by zccoder** [comment]
请问一下你有在密集遮挡的数据集上测试过吗？感觉大规模添加mask，会影响结果

**Comment by daixiangzi** [comment]
> 请问一下你有在密集遮挡的数据集上测试过吗？感觉大规模添加mask，会影响结果

我觉得肯定会影响啊，毕竟你的数据集本来是密集遮挡了
