### ISSUE TITLE
Question about Segmentation

### ISSUE THREAD

**Issue by HuaZheLei** [akuxcw/GridMask#10]
Hi, your work is excellent! Could you share detailed hyperparameters for  'GridMask' you use on semantic segmentation experiment. For instance, `rotate = 1, offset=False, ratio = 0.5, mode=0, prob = 1.`.

**Comment by akuxcw** [comment]
d1: 96
  d2: 512
  rotate: 1
  ratio: 0.5
  mode: 1
  prob: 0.75
  st_epochs: 250
  max_epochs: 300

**Comment by HuaZheLei** [comment]
cool!
