### ISSUE TITLE
Some questions about cifar10 classification dataset

### ISSUE THREAD

**Issue by SpursLipu** [akuxcw/GridMask#11]
I find your work mention GridMask achieve great preformance on cifar 10 dataset but I can't get this result. Could you tell me some hyper-parameters in cifar10 dataset like d1, d2, rotate and ratio?

**Comment by curryandsun** [comment]
I got the same issue.I only found ratio=0.4 in the original paper,and I can't get the best result either.

**Comment by akuxcw** [comment]
Already mentioned in #8.
If you cannot find it: (ratio=0.4, d1=24, d2=33, rotate=1, prob=0.8, mode=1, epochs=280)
