### ISSUE TITLE
Question about the size of mask!

### ISSUE THREAD

**Issue by sky-fly97** [akuxcw/GridMask#12]
Hello, when I use the grid mask in **object detection**, I find that the generated **default mask box** is quite large. I have a question. If such a large black box **covers the target**, will it not affect the training? Or do I need to **set the size of the black box according to the bbox size in each sample**, and the size of the black box should not exceed **2 / 3 or 1 / 2** of the minimum target? Do I **need** to think that way?

**Comment by sky-fly97** [comment]
![{HGYH57(MRU8`9EO(Y~VQ{S](https://user-images.githubusercontent.com/55578436/91711170-0a726380-ebb8-11ea-9fcc-faa63a1bcfbe.png)

**Comment by sky-fly97** [comment]
![image](https://user-images.githubusercontent.com/55578436/91711285-40174c80-ebb8-11ea-87d7-dcc96724d0cb.png)
![image](https://user-images.githubusercontent.com/55578436/91711414-6c32cd80-ebb8-11ea-9459-71cf40411e12.png)

**Comment by akuxcw** [comment]
Hello, the default setting is suitable for COCO dataset. This may because the original training of COCO is easy to overfit, even removing some objects hardly affects the training. If you are using other datasets, you may decrease the mask box. But in my opinion, 1 / 2 of the minimum target is too small (in COCO the smallest object‘s side length is smaller than 30 ). If you find the default setting will cause underfitting in your experiments, maybe decrease the probability of applying GridMask is a better way.

**Comment by sky-fly97** [comment]
> Hello, the default setting is suitable for COCO dataset. This may because the original training of COCO is easy to overfit, even removing some objects hardly affects the training. If you are using other datasets, you may decrease the mask box. But in my opinion, 1 / 2 of the minimum target is too small (in COCO the smallest object‘s side length is smaller than 30 ). If you find the default setting will cause underfitting in your experiments, maybe decrease the probability of applying GridMask is a better way.

Thanks very much!!!  Another question is that if my ori train process is 18 epoch, and I use grid mask at 0.8 prob, do I need to set epoch to twice or more?

**Comment by akuxcw** [comment]
Usually, double the training time will increase the performance with GridMask. For your reference, in COCO the performance will increase until 4X original training time.

**Comment by sky-fly97** [comment]
> Usually, double the training time will increase the performance with GridMask. For your reference, in COCO the performance will increase until 4X original training time.

Thanks,  I got it！

**Comment by sky-fly97** [comment]
> Usually, double the training time will increase the performance with GridMask. For your reference, in COCO the performance will increase until 4X original training time.

I'm sorry for the last question. Does grid mask need to be placed after image normalization, that is, at the end of all augments？

**Comment by akuxcw** [comment]
Yes, GridMask should be placed after normalization.
