### ISSUE TITLE
Missing some hyper-parameters associated with other augmentation transformations.

### ISSUE THREAD

**Issue by nico-zck** [akuxcw/GridMask#18]
In your paper, you state that other augmentation methods are applied in the statement of GridMask.
> The baseline augmentation including randomly deforming the brightness, contrast, saturation, and hue of the input image. And then the image is randomly scaled into a certain range. After that, a horizontal ﬂip operation is randomly applied to the scaled image. Finally, the image is normalized to around zero. Our GridMask is used after the baseline augmentation.

However, I only find that hyper-parameters related to these argumentation transforms were set to disabled.
```python
# Image ColorJitter
_C.INPUT.BRIGHTNESS = 0.0
_C.INPUT.CONTRAST = 0.0
_C.INPUT.SATURATION = 0.0
_C.INPUT.HUE = 0.0

_C.INPUT.VERTICAL_FLIP_PROB_TRAIN = 0.0

```

So, how did you set these hyper-parameters during the experiments?

**Comment by akuxcw** [comment]
This should be a mistake in the paper. Thank you!
We checked the code and find that it allows color jitter, so we clarified like that in the paper. But actually, we didn't use these augmentations.

**Comment by nico-zck** [comment]
@akuxcw Thank you for your explanation. I will close this issue later.

BTW, I'm so curious about the empirical results that whether other argumentations can improve or weaken the final performance？
