### ISSUE TITLE
cifar10复现不出结果

### ISSUE THREAD

**Issue by hero-y** [akuxcw/GridMask#8]
你好，我在cifar10上使用了你的方法训练，其中的参数有(type='GridMask',d1=10, d2=30, ratio = 0.4, mode=1, prob=0.8, max_epochs =150)，但结果甚至没有baseline好，请问是参数设置的问题嘛？(顺便问一下，这篇文章投到哪里去了？)

**Comment by akuxcw** [comment]
首先epochs要大一些（280），其次d的取值大一些（24，32）
