### ISSUE TITLE
关于检测中gridmask超参的问题

### ISSUE THREAD

**Issue by littletomatodonkey** [akuxcw/GridMask#9]
您好，我按照yml文件中的超参，复现之后2x r50只有0.5%的mAP提升（论文中是0.9%），我看了下分类中的超参，gridmask的rotate为360，而在检测中是1，想问下给出的检测中的rotate超参是否有问题呢？

**Comment by akuxcw** [comment]
我们report的结果就是基于rotate=1的，不知道您是否可以再试一次或者尝试4x的结果，因为我们这边跑过很多次感觉结果还是比较稳定的。

**Comment by littletomatodonkey** [comment]
嗯嗯 4x的实验我也跑了，涨幅是0.9%，不知道是否是我设置的问题，我再check下，多谢~
